### ISSUE TITLE
XCode 7.3 beta 3 (7D141) issues

### ISSUE THREAD

**Issue by edgardec** [simonprickett/barttv#1]
Steps I made
Dowload .zip, unzip open the project
![screen shot 2016-05-17 at 08 01 59](https://cloud.githubusercontent.com/assets/5205025/15320227/c4fbc6d8-1c05-11e6-9d2f-b2091c197434.png)
As you could see all issues say Expected ',' separator and Expected expression in list of expressions.
Sorry , but i new to this and can get XCode do not complain.

**Comment by simonprickett** [comment]
I think you're using an older Swift, try using XCode 7.3.1, or change the code on those two lines for older Swift - see "Renamed debug identifiers" here https://swift.org/blog/swift-2-2-new-features/

**Comment by edgardec** [comment]
Thanks for quick answer.
Here how i get Xcode do not complain
Release your two lines by

 func appController(appController: TVApplicationController, didFinishLaunchingWithOptions options: [String: AnyObject]?) {
        print("(**FUNCTION**) invoked with options: (options)")
    }
    
    func appController(appController: TVApplicationController, didFailWithError error: NSError) {
        print("(**FUNCTION**) invoked with error: (error)")
  
Plan to extend your app ? As never go to SF , a tourist view of places could be nice.
Again thanks and any a beginner could made for help , say the word
-- 
Edgar De Cleene
Sent with Airmail

On May 17, 2016 at 13:22:50, Simon Prickett (notifications@github.com) wrote:

I think you're using an older Swift, try using XCode 7.3.1, or change the code on those two lines for older Swift - see "Renamed debug identifiers" here https://swift.org/blog/swift-2-2-new-features/

**Comment by simonprickett** [comment]
Yes, I'd like to spend some time styling it a bit and get some better maps, maybe some sort of instagram slideshow not sure really.  Was mostly a "how does this stuff work" experiment more than something I intend to launch.

**Comment by edgardec** [comment]
Ok. 
It’s ok use data on bart.crudworks.org ?
As I work with Squeak, have in the works a Squeak server/helper for made TVML templates.

-- 
Edgar De Cleene
Sent with Airmail

On May 17, 2016 at 17:42:24, Simon Prickett (notifications@github.com) wrote:

Yes, I'd like to spend some time styling it a bit and get some better maps, maybe some sort of instagram slideshow not sure really. Was mostly a "how does this stuff work" experiment more than something I intend to launch.

**Comment by simonprickett** [comment]
Yes, you can use the data there, it calls the underlying BART API which is an XML one.  However, I don't monitor uptime, performance or accuracy closely on that URL so it may die at any point for an unspecified amount of time (although it's generally reliable).  You can also clone its repo and run your own wherever you like too https://github.com/simonprickett/bartnodeapi

**Comment by edgardec** [comment]
Very thanks.
When have a Squeak way of doing closely original project put demo  video on YouTube.

-- 
Edgar De Cleene
Sent with Airmail

On May 17, 2016 at 20:19:49, Simon Prickett (notifications@github.com) wrote:

Yes, you can use the data there, it calls the underlying BART API which is an XML one. However, I don't monitor uptime, performance or accuracy closely on that URL so it may die at any point for an unspecified amount of time (although it's generally reliable). You can also clone its repo and run your own wherever you like too https://github.com/simonprickett/bartnodeapi
